# Generated by Django 6.0.4 on 2026-04-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_gym_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('easy_run', 'Easy Run'), ('intervals', 'Intervals'), ('long_run', 'Long Run'), ('tempo', 'Tempo Run'), ('rest', 'Rest Day'), ('speed', 'Speed Work'), ('hill', 'Hill Repeats'), ('recovery', 'Recovery Run')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('week_number', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
